### ISSUE TITLE
hardcoded path in CMakeList.txt file

### ISSUE THREAD

**Issue by andraghetti** [HTLife/PangoCloud#1]
Hi! 

You hardcoded your paths in CMakeList.txt file.
`set(OpenCV_DIR /home/jacky/code/KintinuousExt/deps/opencv-2.4.9/build)
INCLUDE_DIRECTORIES(/home/jacky/code/KintinuousExt/deps/opencv-2.4.9/build/include)
set(OpenCV_INCLUDE_DIRS /home/jacky/code/KintinuousExt/deps/opencv-2.4.9/build/include)
set(OpenCV_LIBS /home/jacky/code/KintinuousExt/deps/opencv-2.4.9/build/lib)`

If you remove them, the code will work for everyone :)

**Comment by HTLife** [comment]
Thanks for reminding me!
I already remove this hardcoded path.
